apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
spec:
  replicas: 2 # Cambia el número de réplicas según tus necesidades
  selector:
    matchLabels:
      app: mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb-container
          image: mongo:6.0.9-jammy
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_URI
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "768Mi"
              cpu: "250m"
          volumeMounts:
            - name: mongodb-persistent-storage
              mountPath: /data/db
      volumes:
        - name: mongodb-persistent-storage
          persistentVolumeClaim:
            claimName: mongodb-pv-claim

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
  namespace: demo
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  selector:
    app: mongodb
